name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on:
  schedule:
    -
      cron: '30 0 * * *'
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      -
        name: 'Use Node.js 16.x'
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Update
        run: |
          npx stargazed -u nurgasemetey -t ${{ secrets.GITHUB_TOKEN }} -r awesome-stars -m "docs: stargazed update" -s
#       -
#         name: 'Install Package'
#         run: 'npm install --global stargazed'
#       -
#         name: 'Update Repo'
#         env:
#           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#         run: 'stargazed --username  "nurgasemetey" --token ${GITHUB_TOKEN} --repo "github-stars" --message "stargazed update by GitHub Actions Workflow" --sort'
